language: ruby
services: docker
cache:
- bundler
before_install:
  gem install bundler -v 2.1
install:
- bundle install
rvm:
- 2.3.0
- 2.4.1
notifications:
  email: false
script:
- bundle exec rake default
- gem build sensu-plugins-aws.gemspec
- gem install sensu-plugins-aws-*.gem
before_deploy:
- bash -c "[ ! -d bonsai/ ] && git clone https://github.com/sensu/sensu-go-bonsai-asset.git bonsai || echo 'bonsai/ exists, skipping git clone'"
deploy:
- provider: rubygems
  api_key:
    secure: P+HLvK5cpldG0mivBdnd95VC+43efrx/zIHSuatHwW0GoazdWqtzdtwHLTykSb1QnsuKACpzGEmJXf67P0MGuRL+ZpZ+RTKGfO/7B4NVzdmuVaBxOF5B3Wukf59KcU44+67blUfKcUWZcRRpsUdFxMuulOwHfUc8vKQGoCDfCSbUe1FMnoszuun7U6Ean/SOKugcu3iX+LNp1gfjvqiyqTSUmnnOrBODbWhP4/UP5WQkV26iRqdGk9+GcxOKJT4nSijJDMGdyTXwIXS71CBhf44g5YzIk712kqA+9fkMjHmZIqDBHTaRKOdG4LaS86tMsM6ndmNA3IV5Vx/FJys7MjJ2n2QfDYcLmY/1tF5GCh5XuDHVDSAy3JPRDELkhcwn7pwFclMvxc/Ucp77to2k0JjhKTuQgJJTaRUbTkBWKyk5izMW+aU+4ys63EXRjiKxOq0cBx1HwSDTlpIQVuk4Rdw2bzmPHVpewV9Ny6K8oVFT+COTnlYB6lgSd4FOwECiL8KtjsY8VXERROspmblJE8X/j7K8CIPz4k2vn3myxlKdpSx63HL3eTDwoxomyMIgqyudTQIJd+I+zrQLv+tubeCg6XvDljI508YvEn3mm6c2y6eBvzgmfyJpTrblnDuicqYSZLx85dROX+EAZP0FqsE/TFt2mfRU370sy3xngSA=
  gemspec: sensu-plugins-aws.gemspec
  on:
    tags: true
    all_branches: true
    rvm: 2.3.0
    rvm: 2.4.1
    repo: boutetnico/sensu-plugins-aws
- provider: script
  script: bonsai/ruby-runtime/travis-build-ruby-plugin-assets.sh sensu-plugins-aws-boutetnico
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    rvm: 2.4.1
